project:
  type: website
  output-dir: docs

website:
  title: "HI!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hw2.qmd
        text: hw2
      - href: about.qmd
        text: about

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

